env: "debug"

server:
  port: "8000"
  timeout: 10s
  iddle_timeout: 30s

storage:
  path: "postgres://postgres:qwerty@localhost:5432/MoveDB"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "3h"

redis:
  url: ""
  password: ""
  db: ""
  timeout: ""

jwt: ""

features:
  enable_swagger: true
  enable_quests: true
  enable_cache: true
  enable_metrics: false

quests:
